### PR TITLE
SS 3.7 & PHP 7.2 compatibility.

### PR DESCRIPTION
**Pull request by bummzack**
See: https://docs.silverstripe.org/en/3/changelogs/3.7.0/#for-module-authors

### CODE REVIEW

**Comment by dhensby** [comment]
Thanks, though this module isn't really supported anymore ;)

**Comment by bummzack** [comment]
I know… still using it in a project though :) Thanks for merging ❤️

**Comment by bummzack** [comment]
Hm, doesn't seem to trigger an automatic update on packagist. Maybe a manual update is needed?

**Comment by dhensby** [comment]
I don't appear to be an admin on packagist, so I can't help there. @chillu / @sminnee

**Pull request merged**
